"""
split_key.py — turn a 32-byte AES key into 3 XOR shares for the split-key
hardening (see split-key-storage.md). The key is reconstructed at runtime as
SHARE_A ^ SHARE_B ^ SHARE_C, so no single 32-byte key sits in the binary at rest.

Any 1 or 2 shares reveal nothing about the key (information-theoretically secure
secret split); you need all three.

Usage:
  python split_key.py <64-hex-key>  > script_encryption_shares.gen.h
  # or generate a fresh key and shares:
  python split_key.py --new         > script_encryption_shares.gen.h

Then #include the generated header where you reconstruct the key (e.g. in your
modified file_access_pack.cpp), and DO NOT commit the generated file.
"""
import sys
import secrets


def emit(name, data):
    body = ", ".join("0x%02x" % b for b in data)
    return "static const unsigned char %s[32] = { %s };\n" % (name, body)


def main():
    args = sys.argv[1:]
    if args and args[0] == "--new":
        key = secrets.token_bytes(32)
        sys.stderr.write("generated key (hex): %s\n" % key.hex())
    elif args and len(args[0]) == 64:
        key = bytes.fromhex(args[0])
    else:
        sys.exit("usage: split_key.py <64-hex-key> | --new")

    a = secrets.token_bytes(32)
    b = secrets.token_bytes(32)
    c = bytes(k ^ x ^ y for k, x, y in zip(key, a, b))
    assert bytes(x ^ y ^ z for x, y, z in zip(a, b, c)) == key

    out = []
    out.append("// Generated by split_key.py — DO NOT COMMIT. Regenerate per build.")
    out.append("// key == GDPCK_SHARE_A ^ GDPCK_SHARE_B ^ GDPCK_SHARE_C")
    out.append("#pragma once")
    out.append("#include <cstdint>")
    out.append("")
    out.append(emit("GDPCK_SHARE_A", a).rstrip())
    out.append(emit("GDPCK_SHARE_B", b).rstrip())
    out.append(emit("GDPCK_SHARE_C", c).rstrip())
    out.append("")
    out.append("static inline void gdpck_reconstruct_key(unsigned char *out32) {")
    out.append("\tfor (int i = 0; i < 32; i++) {")
    out.append("\t\tout32[i] = GDPCK_SHARE_A[i] ^ GDPCK_SHARE_B[i] ^ GDPCK_SHARE_C[i];")
    out.append("\t}")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
